version: '3.9'
services:
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
    redis-insight:
        image: redislabs/redisinsight:latest
        ports:
            - 8001:8001